plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bcp.checkmkagent'
    compileSdk 35

    defaultConfig {
        applicationId 'com.bcp.checkmkagent'
        minSdk 26
        targetSdk 33
        versionCode 8         // Nanti naikkan ke 9 saat rilis v1.3.5
        versionName '1.3.4'   // Nanti ubah ke '1.3.5'
    }

    signingConfigs {
        releaseOrDebug {
            storeFile file('cmkagent.keystore')
            storePassword 'android'
            keyAlias 'cmkagent'
            keyPassword 'android'
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
            versionNameSuffix ''
            signingConfig signingConfigs.releaseOrDebug
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.releaseOrDebug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
